name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Runs only when pushing to main branch
  pull_request:
    branches:
      - main  # Optional: Runs on PR merge to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy to Vercel
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --prod
